### ISSUE TITLE
No feedback on SyntaxError

### ISSUE THREAD

**Issue by romgrk** [GoogleChromeLabs/ndb#95] opened 2018-08-02 22:19 UTC
### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.18
* Platform / OS version: ubuntu 17.04
* Node.js version: 8.9.4

**What steps will reproduce the problem?**

```js
// File: test.js
test()
function test() {
 debugger {
}
```

1. `ndb test.js`

**What is the expected result?**
Some feedback that there is a syntax error

**What happens instead?**
No feedback, nothing happens

**Comment by ak239** [comment] 2018-08-03 02:13
Thanks for your report!
Do you have message like this in console? Would you like to get warning somewhere else in UI?
![image](https://user-images.githubusercontent.com/426418/43620504-f16a30a2-9687-11e8-8b95-bedf9ffd796d.png)

**Comment by romgrk** [comment] 2018-08-03 03:09
No, that's the problem, I don't even get a message in the console, which would be fine.
If you need me to provide additional details for debugging just send me the instructions.

**Comment by ak239** [comment] 2018-08-07 04:48
Thanks for your report, I will close it for now. Feel free to reopen it if it still reproducible on your machine at work.

**Comment by romgrk** [comment] 2018-08-07 19:12
Still able to reproduce (with the same file as above):
![screenshot from 2018-08-07 15-11-37](https://user-images.githubusercontent.com/1423607/43797106-49a7bdd2-9a54-11e8-93fb-2d49f014e3a4.png)

**Comment by romgrk** [comment] 2018-08-07 19:26
Shell: `zsh 5.2 (x86_64-ubuntu-linux-gnu)`
Terminal: `GNOME Terminal 3.24.2 Using VTE version 0.48.4 +GNUTLS -PCRE2`

I get the same issue using regular bash:
![screenshot from 2018-08-07 15-25-35](https://user-images.githubusercontent.com/1423607/43797689-32604110-9a56-11e8-81fa-26807dbcecab.png)

**Comment by ak239** [comment] 2018-08-07 19:59
Thanks! Couple more questions: could you open DevTools on ndb by pressing Ctrl + Shift + I and copy paste console output here if there anything and update to latest ndb version 1.0.20 and verify that it is still reproducible?

**Comment by romgrk** [comment] 2018-08-07 20:38
ndb 1.0.18 console:
![screenshot from 2018-08-07 16-32-44](https://user-images.githubusercontent.com/1423607/43800969-c9e288f0-9a5f-11e8-9ab6-03307557872a.png)

ndb 1.0.20:
![screenshot from 2018-08-07 16-34-10](https://user-images.githubusercontent.com/1423607/43800994-d845e568-9a5f-11e8-9740-b69f9e40c92d.png)

**Comment by ak239** [comment] 2018-08-07 21:03
Thanks! I finally can reproduce it locally and am working on fix.

**Comment by ak239** [comment] 2018-08-08 02:05
It looks to me that the root of the issue is combination of "Pause on exception" toggle, "Blackbox anything outside working directory" checkbox and Node 8.

You can disable "Pause on exception" to get SyntaxError in console.
You can disable "Blackbox anything outside working directory" to get pause inside internal vm.js script.
You can update your node to 10 to get SyntaxError in console even when both features are enabled.

**Comment by ak239** [comment] 2019-06-20 15:10
Unfortunately it is too late to fix Node 8, please use Node 10 if it is possible.

**Closed by ak239** 2019-06-20 15:10 UTC
