### ISSUE TITLE
rpc close when debug  at breakpoint

### ISSUE THREAD

**Issue by spitWind** [GoogleChromeLabs/ndb#247] opened 2019-03-18 03:27 UTC
### Steps to reproduce

**Tell us about your environment:**

* ndb version: 1.0.44
* Platform / OS version: window10  17763.379
* Node.js version: v10.14.2

**What steps will reproduce the problem?**

_Please include code that reproduces the issue._

1.  Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
2.
3.

**What is the expected result?**

**What happens instead?**

**Comment by alexnwalters** [comment] 2019-05-25 17:49
I'm getting the same issue did you ever find a fix?

$ ndb index.js
events.js:174
      throw er; // Unhandled 'error' event
      ^
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
...

**Comment by ak239** [comment] 2019-06-20 04:45
@alexnwalters could you try `1.0.47` ?
@spitWind could you provide more details? Do you have sample script?

**Comment by ak239** [comment] 2019-06-22 01:42
It sounds like duplicate of https://github.com/GoogleChromeLabs/ndb/issues/248 to me. Please comment there if it still a problem with latest `ndb@1.0.48`.

**Closed by ak239** 2019-06-22 01:42 UTC
Labels: bug
